#!/bin/sh

checa()
{
a=$( host $1 |grep -c  " has " )
echo $a 
}


cat adblock_hosts  | awk '{ print $2 }' | while read dominio ; do 

echo -n "$dominio " 
if [ "$(checa $dominio)" = "0" ] ; then 
    echo " - NAO"
else
    echo " - SIM"
fi

done

